using UnityEngine; using UnityEngine.SceneManagement;
public class PauseGUI:GUIScreen{
 int tab=0;string worldName="",saveStatus="";Vector2 scroll;
 void Awake(){worldName=string.IsNullOrEmpty(InfiniteWorldSave.CurrentWorldName)?"My World":InfiniteWorldSave.CurrentWorldName;VoxelBoxSettings.Apply();}
 void OnGUI(){VoxelBoxUI.BeginResponsive();VoxelBoxUI.Backdrop(.55f);Rect r=VoxelBoxUI.Safe(1040,840,30);GUILayout.BeginArea(r,VoxelBoxUI.Panel);GUILayout.Label("THE VOXEL BOX",VoxelBoxUI.Header);GUILayout.Label("PAUSE  •  "+(InfiniteWorldSave.CurrentWorldType==InfiniteWorldSave.WorldType.BlockIsland?"BLOCK ISLAND LEGACY WORLD":InfiniteWorldSave.CurrentWorldType==InfiniteWorldSave.WorldType.Tanviir?"TANVIIR CREATIVE WORLD":"CREATIVE WORLD"),VoxelBoxUI.Small);GUILayout.Space(8);if(GUILayout.Button("▶  WEITERSPIELEN",VoxelBoxUI.Button,GUILayout.Height(44)))GameState.IsPlaying=true;GUILayout.Space(10);tab=VoxelBoxSettingsGUI.DrawTabs(tab);scroll=GUILayout.BeginScrollView(scroll);if(tab==0||tab==2||tab==4||tab==5)VoxelBoxSettingsGUI.Draw(tab,true);else if(tab==1)DrawWorld();else if(tab==3)DrawAudio();GUILayout.EndScrollView();GUILayout.Space(8);if(GUILayout.Button("←  HAUPTMENÜ",VoxelBoxUI.Danger,GUILayout.Height(42))){if(InfiniteWorldSave.CurrentWorldType==InfiniteWorldSave.WorldType.Tanviir || InfiniteWorldSave.CurrentWorldType==InfiniteWorldSave.WorldType.BlockIsland){var w=Map.instance!=null?Map.instance.infiniteWorld:null;if(w!=null){if(InfiniteWorldSave.CurrentWorldType==InfiniteWorldSave.WorldType.BlockIsland)InfiniteWorldSave.SaveBlockIsland(w);else InfiniteWorldSave.SaveTanviir(w);}}Time.timeScale=1;Cursor.lockState=CursorLockMode.None;Cursor.visible=true;SceneManager.LoadScene(0);}GUILayout.EndArea();VoxelBoxUI.EndResponsive();}
 void DrawWorld(){GUILayout.Label("WELT",VoxelBoxUI.Header);var d=InfiniteDayNightCycle.Instance;if(d!=null){GUILayout.Label("Tag & Nacht  •  "+d.ClockText()+"  (1 Tag = 60 Minuten)",VoxelBoxUI.Label);GUILayout.BeginHorizontal();if(GUILayout.Button(d.cycleEnabled?"ZYKLUS: EIN":"ZYKLUS: AUS",VoxelBoxUI.Button,GUILayout.Height(36)))d.SetCycle(!d.cycleEnabled);if(GUILayout.Button("NUR TAG (12:00)",VoxelBoxUI.Button,GUILayout.Height(36)))d.OnlyDay();GUILayout.EndHorizontal();float nv=GUILayout.HorizontalSlider(d.timeOfDay,0,24);if(Mathf.Abs(nv-d.timeOfDay)>.001f)d.SetTime(nv,true);}
  var wth=InfiniteCreativeWeather.Instance;if(wth!=null&&VoxelBoxSettings.WeatherEffects){GUILayout.Space(10);GUILayout.Label("WETTER",VoxelBoxUI.Header);GUILayout.BeginHorizontal();if(GUILayout.Button(wth.rainEnabled?"REGEN: EIN":"REGEN: AUS",VoxelBoxUI.Button,GUILayout.Height(36)))wth.SetRain(!wth.rainEnabled);if(GUILayout.Button(wth.mistEnabled?"NEBEL: EIN":"NEBEL: AUS",VoxelBoxUI.Button,GUILayout.Height(36)))wth.SetMist(!wth.mistEnabled);if(GUILayout.Button("KLARES WETTER",VoxelBoxUI.Button,GUILayout.Height(36)))wth.ClearWeather();GUILayout.EndHorizontal();}
  GUILayout.Space(14);GUILayout.Label("SPEICHERN",VoxelBoxUI.Header);worldName=GUILayout.TextField(worldName,48,GUILayout.Height(32));if(GUILayout.Button("▣  WELT SPEICHERN",VoxelBoxUI.Button,GUILayout.Height(38))){var w=Map.instance!=null?Map.instance.infiniteWorld:null;if(w!=null){worldName=InfiniteWorldSave.SanitizeName(worldName);saveStatus=InfiniteWorldSave.Save(w,worldName)?"Gespeichert: "+worldName:"Speichern fehlgeschlagen";if(InfiniteDayNightCycle.Instance!=null)InfiniteDayNightCycle.Instance.SavePrefs();}}
  if(InfiniteWorldSave.CurrentWorldType==InfiniteWorldSave.WorldType.Tanviir&&GUILayout.Button("▣  TANVIIR SPEICHERN",VoxelBoxUI.Button,GUILayout.Height(38))){var w=Map.instance!=null?Map.instance.infiniteWorld:null;if(w!=null)saveStatus=InfiniteWorldSave.SaveTanviir(w)?"Tanviir gespeichert":"Tanviir speichern fehlgeschlagen";} if(InfiniteWorldSave.CurrentWorldType==InfiniteWorldSave.WorldType.BlockIsland&&GUILayout.Button("▣  BLOCK ISLAND SPEICHERN",VoxelBoxUI.Button,GUILayout.Height(38))){var w=Map.instance!=null?Map.instance.infiniteWorld:null;if(w!=null)saveStatus=InfiniteWorldSave.SaveBlockIsland(w)?"Block Island gespeichert":"Block Island speichern fehlgeschlagen";}if(!string.IsNullOrEmpty(saveStatus))GUILayout.Label(saveStatus,VoxelBoxUI.Label);GUILayout.Label("Savegames: "+InfiniteWorldSave.SaveDirectory,VoxelBoxUI.Small);if(GUILayout.Button("▤  SAVEGAME-ORDNER ÖFFNEN",VoxelBoxUI.Button,GUILayout.Height(36)))InfiniteWorldSave.OpenSaveDirectory();}
 void DrawAudio(){GUILayout.Label("AUDIO",VoxelBoxUI.Header);var m=InfiniteMusicPlayer.Instance;if(m==null){GUILayout.Label("Musikplayer wird initialisiert ...",VoxelBoxUI.Label);return;}GUILayout.BeginHorizontal();if(GUILayout.Button("MP3-ORDNER WÄHLEN",VoxelBoxUI.Button,GUILayout.Height(38)))m.ChooseFolder();GUILayout.Label(string.IsNullOrEmpty(m.folderPath)?"Kein Ordner":m.folderPath,VoxelBoxUI.Small);GUILayout.EndHorizontal();GUILayout.Label("Playlist: "+m.tracks.Count+" / "+InfiniteMusicPlayer.MaxTracks+"   •   "+m.CurrentTitle,VoxelBoxUI.Label);GUILayout.BeginHorizontal();if(GUILayout.Button("|<",VoxelBoxUI.Button))m.Previous();if(GUILayout.Button("PLAY",VoxelBoxUI.Button))m.Play();if(GUILayout.Button("PAUSE",VoxelBoxUI.Button))m.Pause();if(GUILayout.Button("STOP",VoxelBoxUI.Button))m.Stop();if(GUILayout.Button(">|",VoxelBoxUI.Button))m.Next();if(GUILayout.Button(m.shuffle?"SHUFFLE: EIN":"SHUFFLE: AUS",VoxelBoxUI.Button))m.ToggleShuffle();GUILayout.EndHorizontal();GUILayout.Label("Lautstärke  "+Mathf.RoundToInt(m.volume*100)+"%",VoxelBoxUI.Label);float v=GUILayout.HorizontalSlider(m.volume,0,1);if(Mathf.Abs(v-m.volume)>.001f)m.SetVolume(v);}
 void Update(){if(GameState.IsPlaying)SetScreen<GameGUI>();}
}
