using UnityEngine;
using System.IO;
public static class BlockDesignerGUI {
 static int target=1,source=1,sourceTab=0,customSelected=-1; static Vector2 leftScroll,rightScroll; static string status=""; static GameObject menuBlockSet; static string[] customFiles=new string[0];
 // 0.9.9.7f: live 3D preview renderer. It uses the block's real Build() mesh and
 // BlockSet materials, so stairs/fences/spheres/plants are shown as geometry, not as a flat icon.
 static GameObject previewRoot; static Camera previewCamera; static Light previewKey,previewFill; static MeshFilter previewFilter; static MeshRenderer previewRenderer; static RenderTexture previewRT; static Mesh previewMesh; static int previewBlock=-1; static float previewYaw=32f,previewPitch=20f,previewZoom=2.35f;
 static void Ensure3DPreview(){
  if(previewRoot!=null&&previewCamera!=null&&previewRT!=null)return;
  previewRoot=new GameObject("Block Designer 3D Preview"); previewRoot.hideFlags=HideFlags.HideAndDontSave; previewRoot.layer=31;
  previewFilter=previewRoot.AddComponent<MeshFilter>(); previewRenderer=previewRoot.AddComponent<MeshRenderer>(); previewRenderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.On; previewRenderer.receiveShadows=true;
  GameObject cg=new GameObject("Block Designer Preview Camera");cg.hideFlags=HideFlags.HideAndDontSave;cg.layer=31;previewCamera=cg.AddComponent<Camera>();previewCamera.enabled=false;previewCamera.cullingMask=1<<31;previewCamera.clearFlags=CameraClearFlags.SolidColor;previewCamera.backgroundColor=new Color(.025f,.035f,.04f,1);previewCamera.fieldOfView=31f;previewCamera.nearClipPlane=.05f;previewCamera.farClipPlane=20f;
  previewRT=new RenderTexture(320,320,24,RenderTextureFormat.ARGB32);previewRT.name="Block Designer Preview RT";previewRT.hideFlags=HideFlags.HideAndDontSave;previewRT.Create();previewCamera.targetTexture=previewRT;
  GameObject kg=new GameObject("Block Designer Preview Key");kg.hideFlags=HideFlags.HideAndDontSave;kg.layer=31;previewKey=kg.AddComponent<Light>();previewKey.type=LightType.Directional;previewKey.intensity=1.05f;previewKey.cullingMask=1<<31;kg.transform.rotation=Quaternion.Euler(42f,-38f,0);
  GameObject fg=new GameObject("Block Designer Preview Fill");fg.hideFlags=HideFlags.HideAndDontSave;fg.layer=31;previewFill=fg.AddComponent<Light>();previewFill.type=LightType.Directional;previewFill.intensity=.42f;previewFill.cullingMask=1<<31;fg.transform.rotation=Quaternion.Euler(320f,145f,0);
 }
 static bool Rebuild3DPreview(BlockSet set,int id){
  Ensure3DPreview();if(set==null||id<0||id>=set.Count||set[id]==null)return false;Block b=set[id];MeshBuilder mb=null;try{mb=b.Build();}catch(System.Exception e){Debug.LogWarning("Block Designer 3D preview: "+e.Message);}if(mb==null||mb.vertices.Count==0){previewFilter.sharedMesh=null;previewRenderer.sharedMaterials=new Material[0];previewBlock=id;return false;}
  previewMesh=mb.ToMesh(previewMesh);if(previewMesh==null)return false;previewMesh.name="Block Designer Preview Mesh";previewMesh.hideFlags=HideFlags.HideAndDontSave;previewFilter.sharedMesh=previewMesh;previewRenderer.sharedMaterials=mb.GetMaterials(set.GetMaterials());Bounds bo=previewMesh.bounds;previewRoot.transform.position=-bo.center;previewBlock=id;return true;
 }
 static void Draw3DPreview(BlockSet set,int id,Rect r){
  if(previewBlock!=id||previewFilter==null||previewFilter.sharedMesh==null)Rebuild3DPreview(set,id);Ensure3DPreview();
  Event e=Event.current;if(r.Contains(e.mousePosition)){if(e.type==EventType.MouseDrag&&e.button==0){previewYaw+=e.delta.x*.8f;previewPitch=Mathf.Clamp(previewPitch-e.delta.y*.65f,-70f,70f);e.Use();}else if(e.type==EventType.ScrollWheel){previewZoom=Mathf.Clamp(previewZoom+e.delta.y*.10f,1.45f,4.2f);e.Use();}}
  GUI.Box(r,GUIContent.none);if(previewFilter.sharedMesh==null){GUI.Label(new Rect(r.x+8,r.y+55,r.width-16,45),"Für diesen Slot ist kein Block-Mesh hinterlegt.",VoxelBoxUI.Small);return;}
  Quaternion orbit=Quaternion.Euler(previewPitch,previewYaw,0);Vector3 dir=orbit*new Vector3(0,0,-1);previewCamera.transform.position=dir*previewZoom;previewCamera.transform.LookAt(Vector3.zero,Vector3.up);previewCamera.Render();GUI.DrawTexture(new Rect(r.x+4,r.y+4,r.width-8,r.height-8),previewRT,ScaleMode.ScaleToFit,false);GUI.Label(new Rect(r.x+7,r.y+r.height-23,r.width-14,20),"Ziehen: drehen  •  Mausrad: Zoom",VoxelBoxUI.Small);
 }
 static BlockSet EnsureBlockSet(){if(BlockSet.instance!=null)return BlockSet.instance;GameObject prefab=Resources.Load<GameObject>("BlockSet");if(prefab==null)return null;menuBlockSet=Object.Instantiate(prefab);menuBlockSet.name="BlockSet (Main Menu Preview)";RefreshFiles();return BlockSet.instance!=null?BlockSet.instance:menuBlockSet.GetComponent<BlockSet>();}
 static void RefreshFiles(){BlockTextureDesigner.ReloadCustomTextures();customFiles=BlockTextureDesigner.CustomFiles();if(customSelected>=customFiles.Length)customSelected=customFiles.Length-1;status=customFiles.Length+" eigene PNG-Textur(en) gefunden.";}
 public static void Draw(){
  BlockSet set=EnsureBlockSet();if(set==null){GUILayout.Label("BlockSet konnte nicht geladen werden.",VoxelBoxUI.Label);return;}if(set.Count<=0)return;target=Mathf.Clamp(target,0,set.Count-1);source=Mathf.Clamp(source,0,set.Count-1);Block tb=set[target];
  GUILayout.BeginHorizontal();
  GUILayout.BeginVertical(VoxelBoxUI.Card,GUILayout.Width(250));VoxelBoxUI.SectionTitle("1. BLOCK AUSWÄHLEN");leftScroll=GUILayout.BeginScrollView(leftScroll,GUILayout.Height(520));for(int i=0;i<set.Count;i++){Block b=set[i];if(b==null)continue;if(GUILayout.Button("ID "+i.ToString("000")+"   "+b.name,(i==target?VoxelBoxUI.TabActive:VoxelBoxUI.Tab),GUILayout.Height(30))){target=i;tb=b;if(!BlockTextureDesigner.Compatible(tb,set[source]))source=target;status="";}}GUILayout.EndScrollView();GUILayout.EndVertical();GUILayout.Space(8);
  GUILayout.BeginVertical(VoxelBoxUI.Card,GUILayout.Width(300));VoxelBoxUI.SectionTitle("VORSCHAU");GUILayout.Label("ID "+target.ToString("000")+"  •  "+tb.name,VoxelBoxUI.Label);GUILayout.Label("Grundstruktur: "+BlockTextureDesigner.Structure(tb),VoxelBoxUI.Small);Rect pr=GUILayoutUtility.GetRect(176,176,GUILayout.ExpandWidth(false));Draw3DPreview(set,target,pr);string cf=BlockTextureDesigner.OverrideCustom(target);int ov=BlockTextureDesigner.OverrideSource(target);GUILayout.Label(!string.IsNullOrEmpty(cf)?"Eigene Textur: "+cf:(ov<0?"Textur: ORIGINAL":"Vorlage: ID "+ov.ToString("000")+" – "+set[ov].name),VoxelBoxUI.Label);if(GUILayout.Button("ORIGINAL WIEDERHERSTELLEN",VoxelBoxUI.Danger,GUILayout.Height(38))){status=BlockTextureDesigner.Restore(set,target)?"Originaltextur wiederhergestellt.":"Original ist bereits aktiv.";previewBlock=-1;}GUILayout.Space(5);GUILayout.Label("Globale Zuordnung – gilt in allen Welten.",VoxelBoxUI.Small);GUILayout.EndVertical();GUILayout.Space(8);
  GUILayout.BeginVertical(VoxelBoxUI.Card,GUILayout.Width(500));VoxelBoxUI.SectionTitle("2. TEXTURQUELLE");GUILayout.BeginHorizontal();if(GUILayout.Button("SPIEL-ATLANTEN",sourceTab==0?VoxelBoxUI.TabActive:VoxelBoxUI.Tab,GUILayout.Height(36),GUILayout.ExpandWidth(true)))sourceTab=0;if(GUILayout.Button("EIGENE PNG",sourceTab==1?VoxelBoxUI.TabActive:VoxelBoxUI.Tab,GUILayout.Height(36),GUILayout.ExpandWidth(true)))sourceTab=1;GUILayout.EndHorizontal();GUILayout.Space(5);
  if(sourceTab==0)DrawBuiltIns(set,tb);else DrawCustom(set,tb);
  if(!string.IsNullOrEmpty(status))GUILayout.Label(status,VoxelBoxUI.Small);GUILayout.EndVertical();GUILayout.EndHorizontal();
 }
 static void DrawBuiltIns(BlockSet set,Block tb){GUILayout.Label("Vorhandene Texturen des Spiels. Es werden passende Grundstrukturen angeboten.",VoxelBoxUI.Small);rightScroll=GUILayout.BeginScrollView(rightScroll,GUILayout.Height(350));for(int i=0;i<set.Count;i++){Block b=set[i];if(b==null||!BlockTextureDesigner.Compatible(tb,b))continue;GUILayout.BeginHorizontal();Rect rr=GUILayoutUtility.GetRect(38,38,GUILayout.Width(38));b.DrawPreview(rr);if(GUILayout.Button("ID "+i.ToString("000")+"  "+b.name,(i==source?VoxelBoxUI.TabActive:VoxelBoxUI.Tab),GUILayout.Height(38)))source=i;GUILayout.EndHorizontal();}GUILayout.EndScrollView();GUILayout.Label("Vorlage: ID "+source.ToString("000")+" – "+set[source].name,VoxelBoxUI.Label);if(GUILayout.Button("TEXTUR ÜBERNEHMEN",VoxelBoxUI.Button,GUILayout.Height(44))){status=BlockTextureDesigner.Apply(set,target,source)?"Globale Textur gespeichert.":"Grundstrukturen nicht kompatibel.";previewBlock=-1;}}
 static void DrawCustom(BlockSet set,Block tb){GUILayout.Label("Eigene PNG-Texturen",VoxelBoxUI.Label);GUILayout.Label("Ordner: Dokumente / Block Island / BlockTextures / Textures",VoxelBoxUI.Small);GUILayout.Label("PNG hineinlegen und danach NEU LADEN wählen.",VoxelBoxUI.Small);GUILayout.BeginHorizontal();if(GUILayout.Button("ORDNER ÖFFNEN",VoxelBoxUI.Button,GUILayout.Height(34),GUILayout.ExpandWidth(true)))BlockTextureDesigner.OpenTextureFolder();if(GUILayout.Button("NEU LADEN",VoxelBoxUI.Tab,GUILayout.Height(34),GUILayout.Width(120)))RefreshFiles();GUILayout.EndHorizontal();GUILayout.Space(5);rightScroll=GUILayout.BeginScrollView(rightScroll,GUILayout.Height(300));if(customFiles.Length==0)GUILayout.Label("Noch keine PNG-Dateien gefunden.",VoxelBoxUI.Label);for(int i=0;i<customFiles.Length;i++){Texture2D t=BlockTextureDesigner.LoadCustomTexture(customFiles[i]);GUILayout.BeginHorizontal();Rect rr=GUILayoutUtility.GetRect(48,48,GUILayout.Width(48));if(t!=null)GUI.DrawTexture(rr,t,ScaleMode.ScaleToFit,true);string n=Path.GetFileName(customFiles[i]);if(GUILayout.Button(n,(i==customSelected?VoxelBoxUI.TabActive:VoxelBoxUI.Tab),GUILayout.Height(48)))customSelected=i;GUILayout.EndHorizontal();}GUILayout.EndScrollView();if(customSelected>=0&&customSelected<customFiles.Length){GUILayout.Label("Ausgewählt: "+Path.GetFileName(customFiles[customSelected]),VoxelBoxUI.Small);if(GUILayout.Button("EIGENE TEXTUR ÜBERNEHMEN",VoxelBoxUI.Button,GUILayout.Height(44))){status=BlockTextureDesigner.ApplyCustom(set,target,customFiles[customSelected])?"Eigene Textur global gespeichert.":"PNG konnte nicht angewendet werden.";previewBlock=-1;}}else GUILayout.Label("PNG auswählen, um sie auf den gewählten Block zu legen.",VoxelBoxUI.Small);}
}
