using System; using System.IO; using System.IO.Compression; using System.Text; using System.Collections.Generic;

// Minimal big-endian NBT reader used only by the Block Island Minecraft importer.
public sealed class MinecraftNbt {
 public sealed class Tag { public byte type; public object value; public Dictionary<string,Tag> Compound { get { return value as Dictionary<string,Tag>; } } public List<Tag> List { get { return value as List<Tag>; } } public Tag Get(string n){Tag t;return Compound!=null&&Compound.TryGetValue(n,out t)?t:null;} public int Int(int d=0){return value is int?(int)value:value is byte?(byte)value:value is short?(short)value:d;} public long Long(long d=0){return value is long?(long)value:d;} public string String(string d=""){return value as string??d;} }
 sealed class BE { readonly BinaryReader r; public BE(Stream s){r=new BinaryReader(s);} public byte B(){return r.ReadByte();} public short S(){byte[] b=r.ReadBytes(2);return (short)((b[0]<<8)|b[1]);} public int I(){byte[] b=r.ReadBytes(4);return (b[0]<<24)|(b[1]<<16)|(b[2]<<8)|b[3];} public long L(){byte[] b=r.ReadBytes(8);ulong v=0;for(int i=0;i<8;i++)v=(v<<8)|b[i];return unchecked((long)v);} public float F(){byte[] b=r.ReadBytes(4);Array.Reverse(b);return BitConverter.ToSingle(b,0);} public double D(){byte[] b=r.ReadBytes(8);Array.Reverse(b);return BitConverter.ToDouble(b,0);} public string Str(){int n=(ushort)S();return Encoding.UTF8.GetString(r.ReadBytes(n));} public byte[] Bytes(int n){return r.ReadBytes(n);} }
 public static Tag Read(byte[] raw){using(var ms=new MemoryStream(raw)){var b=new BE(ms);byte type=b.B();if(type==0)return null;b.Str();return Payload(b,type);}}
 static Tag Payload(BE b,byte t){var x=new Tag();x.type=t;switch(t){case 1:x.value=b.B();break;case 2:x.value=b.S();break;case 3:x.value=b.I();break;case 4:x.value=b.L();break;case 5:x.value=b.F();break;case 6:x.value=b.D();break;case 7:{int n=b.I();x.value=b.Bytes(n);break;}case 8:x.value=b.Str();break;case 9:{byte et=b.B();int n=b.I();var a=new List<Tag>(Math.Max(0,n));for(int i=0;i<n;i++)a.Add(Payload(b,et));x.value=a;break;}case 10:{var d=new Dictionary<string,Tag>();while(true){byte et=b.B();if(et==0)break;string n=b.Str();d[n]=Payload(b,et);}x.value=d;break;}case 11:{int n=b.I();int[] a=new int[n];for(int i=0;i<n;i++)a[i]=b.I();x.value=a;break;}case 12:{int n=b.I();long[] a=new long[n];for(int i=0;i<n;i++)a[i]=b.L();x.value=a;break;}default:throw new InvalidDataException("NBT tag "+t+" unsupported");}return x;}
 public static byte[] DecompressChunk(byte compression,byte[] src){if(compression==3)return src;using(var input=new MemoryStream(src)){Stream zs;if(compression==1)zs=new GZipStream(input,CompressionMode.Decompress);else if(compression==2){if(src.Length<6)throw new InvalidDataException("Invalid zlib stream");input.Position=2;zs=new DeflateStream(new MemoryStream(src,2,src.Length-6,false),CompressionMode.Decompress);}else throw new InvalidDataException("Minecraft compression "+compression+" unsupported");using(zs)using(var output=new MemoryStream()){zs.CopyTo(output);return output.ToArray();}}}
}
