using System; using System.IO; using System.IO.Compression; using System.Collections.Generic;

// Reads MCEdit .schematic, Sponge .schem (v1-v3) and Litematica .litematic files.
public static class MinecraftStructureReader {
 public struct Structure { public List<MinecraftRegionReader.McBlock> blocks; public int minX,minY,minZ,maxX,maxY,maxZ; public string format; }
 public static bool TryRead(string path,out Structure s,out string error){s=new Structure{blocks=new List<MinecraftRegionReader.McBlock>(),minX=int.MaxValue,minY=int.MaxValue,minZ=int.MaxValue,maxX=int.MinValue,maxY=int.MinValue,maxZ=int.MinValue,format=""};error="";try{
   byte[] raw=ReadNbtFile(path);var root=MinecraftNbt.Read(raw);if(root==null)throw new InvalidDataException("Leere NBT-Datei.");string ext=Path.GetExtension(path).ToLowerInvariant();
   if(ext==".litematic"){s.format="Litematica";ReadLitematic(root,ref s);} else if(ext==".schem"){s.format="Sponge Schematic";ReadSponge(root,ref s);} else {s.format="MCEdit Schematic";ReadClassic(root,ref s);}
   if(s.blocks.Count==0){error="Die Datei enthält keine importierbaren Blöcke.";return false;}return true;
  }catch(Exception e){error=e.Message;return false;}}
 static byte[] ReadNbtFile(string p){byte[] src=File.ReadAllBytes(p);if(src.Length>=2&&src[0]==0x1f&&src[1]==0x8b){using(var input=new MemoryStream(src))using(var gz=new GZipStream(input,CompressionMode.Decompress))using(var output=new MemoryStream()){gz.CopyTo(output);return output.ToArray();}}return src;}
 static void Add(ref Structure s,int x,int y,int z,string name,Dictionary<string,string> state=null){if(IsAir(name))return;var b=new MinecraftRegionReader.McBlock{x=x,y=y,z=z,name=name,state=state};s.blocks.Add(b);s.minX=Math.Min(s.minX,x);s.minY=Math.Min(s.minY,y);s.minZ=Math.Min(s.minZ,z);s.maxX=Math.Max(s.maxX,x);s.maxY=Math.Max(s.maxY,y);s.maxZ=Math.Max(s.maxZ,z);}
 static void ReadClassic(MinecraftNbt.Tag root,ref Structure s){int w=I(root,"Width"),h=I(root,"Height"),l=I(root,"Length");byte[] blocks=Bytes(root,"Blocks"),data=Bytes(root,"Data"),add=Bytes(root,"AddBlocks");if(w<=0||h<=0||l<=0||blocks==null)throw new InvalidDataException("Ungültige alte .schematic-Datei.");int n=Math.Min(blocks.Length,w*h*l);for(int i=0;i<n;i++){int id=blocks[i];if(add!=null){int p=i>>1;if(p<add.Length)id|=((i&1)==0?(add[p]&15):((add[p]>>4)&15))<<8;}if(id==0)continue;int md=data!=null&&i<data.Length?data[i]&15:0;int x=i%w,z=(i/w)%l,y=i/(w*l);Add(ref s,x,y,z,LegacyName(id,md));}}
 static void ReadSponge(MinecraftNbt.Tag root,ref Structure s){var schem=root.Get("Schematic")??root;int w=I(schem,"Width"),h=I(schem,"Height"),l=I(schem,"Length");var blocksNode=schem.Get("Blocks");var pal=(blocksNode!=null?blocksNode.Get("Palette"):null)??schem.Get("Palette");byte[] encoded=(blocksNode!=null?Bytes(blocksNode,"Data"):null)??Bytes(schem,"BlockData");if(w<=0||h<=0||l<=0||pal==null||pal.Compound==null||encoded==null)throw new InvalidDataException("Sponge .schem Palette/BlockData nicht gefunden.");var names=new Dictionary<int,string>();foreach(var kv in pal.Compound)names[kv.Value.Int()]=kv.Key;int pos=0,count=w*h*l;for(int i=0;i<count&&pos<encoded.Length;i++){int pi=ReadVarInt(encoded,ref pos);string spec;if(!names.TryGetValue(pi,out spec))continue;string name;Dictionary<string,string> state;ParseState(spec,out name,out state);int x=i%w,z=(i/w)%l,y=i/(w*l);Add(ref s,x,y,z,name,state);}}
 static void ReadLitematic(MinecraftNbt.Tag root,ref Structure s){var regions=root.Get("Regions");if(regions==null||regions.Compound==null)throw new InvalidDataException("Litematic Regions nicht gefunden.");foreach(var rk in regions.Compound){var r=rk.Value;var pos=r.Get("Position");var size=r.Get("Size");var palette=r.Get("BlockStatePalette");var states=r.Get("BlockStates");if(size==null||palette==null||palette.List==null||states==null)continue;int px=C(pos,"x"),py=C(pos,"y"),pz=C(pos,"z"),sx=C(size,"x"),sy=C(size,"y"),sz=C(size,"z");int ax=Math.Abs(sx),ay=Math.Abs(sy),az=Math.Abs(sz);if(ax==0||ay==0||az==0)continue;long[] packed=states.value as long[];if(packed==null)continue;int bits=Math.Max(2,CeilLog2(palette.List.Count));int volume=ax*ay*az;for(int i=0;i<volume;i++){int pi=PackedIndex(packed,i,bits);if(pi<0||pi>=palette.List.Count)continue;var pe=palette.List[pi];string name=(pe.Get("Name")??pe.Get("name"))!=null?(pe.Get("Name")??pe.Get("name")).String():"minecraft:air";Dictionary<string,string> st=null;var props=pe.Get("Properties")??pe.Get("properties");if(props!=null&&props.Compound!=null){st=new Dictionary<string,string>();foreach(var kv in props.Compound)st[kv.Key]=kv.Value.String();}int lx=i%ax,lz=(i/ax)%az,ly=i/(ax*az);int x=px+(sx<0?-lx:lx),y=py+(sy<0?-ly:ly),z=pz+(sz<0?-lz:lz);Add(ref s,x,y,z,name,st);}}}
 static int PackedIndex(long[] a,int index,int bits){long bit=(long)index*bits;int word=(int)(bit>>6),off=(int)(bit&63);if(word>=a.Length)return 0;ulong mask=(1UL<<bits)-1,v=(ulong)a[word]>>off;if(off+bits>64&&word+1<a.Length)v|=(ulong)a[word+1]<<(64-off);return (int)(v&mask);}
 static int ReadVarInt(byte[] a,ref int p){int v=0,shift=0;while(p<a.Length&&shift<35){int b=a[p++];v|=(b&127)<<shift;if((b&128)==0)return v;shift+=7;}return v;}
 static void ParseState(string spec,out string name,out Dictionary<string,string> st){st=null;int q=spec.IndexOf('[');if(q<0){name=spec;return;}name=spec.Substring(0,q);int e=spec.LastIndexOf(']');if(e<=q)return;st=new Dictionary<string,string>();foreach(string part in spec.Substring(q+1,e-q-1).Split(',')){int k=part.IndexOf('=');if(k>0)st[part.Substring(0,k)]=part.Substring(k+1);}}
 static int I(MinecraftNbt.Tag t,string n){var x=t!=null?t.Get(n):null;return x!=null?x.Int():0;} static int C(MinecraftNbt.Tag t,string n){return I(t,n);} static byte[] Bytes(MinecraftNbt.Tag t,string n){var x=t!=null?t.Get(n):null;return x!=null?x.value as byte[]:null;} static int CeilLog2(int v){int b=0,x=Math.Max(1,v)-1;while(x>0){b++;x>>=1;}return b;} static bool IsAir(string n){return String.IsNullOrEmpty(n)||n=="minecraft:air"||n=="minecraft:cave_air"||n=="minecraft:void_air";}
 static string LegacyName(int id,int data){switch(id){case 1:return "minecraft:stone";case 2:return "minecraft:grass_block";case 3:return "minecraft:dirt";case 4:return "minecraft:cobblestone";case 5:return "minecraft:oak_planks";case 7:return "minecraft:bedrock";case 8:case 9:return "minecraft:water";case 10:case 11:return "minecraft:lava";case 12:return "minecraft:sand";case 13:return "minecraft:gravel";case 14:return "minecraft:gold_ore";case 15:return "minecraft:iron_ore";case 16:return "minecraft:coal_ore";case 17:return data==2?"minecraft:birch_log":data==1?"minecraft:spruce_log":"minecraft:oak_log";case 18:return data==2?"minecraft:birch_leaves":data==1?"minecraft:spruce_leaves":"minecraft:oak_leaves";case 20:return "minecraft:glass";case 24:return "minecraft:sandstone";case 35:return data==14?"minecraft:red_wool":data==11?"minecraft:blue_wool":data==5?"minecraft:green_wool":"minecraft:white_wool";case 41:return "minecraft:gold_block";case 42:return "minecraft:iron_block";case 45:return "minecraft:bricks";case 49:return "minecraft:obsidian";case 53:return "minecraft:oak_stairs";case 56:return "minecraft:diamond_ore";case 57:return "minecraft:diamond_block";case 67:return "minecraft:cobblestone_stairs";case 79:return "minecraft:ice";case 85:return "minecraft:oak_planks";case 87:return "minecraft:netherrack";case 89:return "minecraft:glowstone";case 98:return "minecraft:stone_bricks";case 112:return "minecraft:nether_bricks";case 121:return "minecraft:end_stone";case 155:return "minecraft:quartz_block";default:return "minecraft:stone";}}
}
