using UnityEngine;
using UnityEngine.Rendering.PostProcessing;
public sealed class VoxelBoxGraphicsRuntime : MonoBehaviour {
 static VoxelBoxGraphicsRuntime instance; PostProcessVolume volume; PostProcessLayer layer; Bloom bloom; AmbientOcclusion ao; ColorGrading grading;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Install(){if(instance!=null)return;var go=new GameObject("VoxelBox Graphics Runtime");DontDestroyOnLoad(go);instance=go.AddComponent<VoxelBoxGraphicsRuntime>();instance.Setup();}
 void Setup(){var cam=Camera.main;if(cam==null){Invoke(nameof(Setup),.25f);return;} layer=cam.GetComponent<PostProcessLayer>();if(layer==null)layer=cam.gameObject.AddComponent<PostProcessLayer>();layer.volumeLayer = 1 << 30; var resources = Resources.Load<PostProcessResources>("PostProcessResources"); if(resources != null) layer.Init(resources);var vg=new GameObject("VoxelBox Post Processing");DontDestroyOnLoad(vg);vg.layer=30;volume=vg.AddComponent<PostProcessVolume>();volume.isGlobal=true;volume.priority=100f;volume.profile=ScriptableObject.CreateInstance<PostProcessProfile>();bloom=volume.profile.AddSettings<Bloom>();ao=volume.profile.AddSettings<AmbientOcclusion>();grading=volume.profile.AddSettings<ColorGrading>();Apply();}
 public static void ApplyCurrent(){if(instance!=null)instance.Apply();}
 void Apply(){if(layer==null||volume==null)return;volume.enabled=VoxelBoxSettings.PostProcessing;bloom.enabled.Override(VoxelBoxSettings.Bloom);bloom.intensity.Override(VoxelBoxSettings.BloomIntensity);bloom.threshold.Override(1.05f);ao.enabled.Override(VoxelBoxSettings.AmbientOcclusion);ao.intensity.Override(VoxelBoxSettings.AOIntensity);ao.radius.Override(0.38f);
 grading.enabled.Override(true);grading.tonemapper.Override(Tonemapper.ACES);grading.temperature.Override(VoxelBoxSettings.Warmth);grading.saturation.Override(VoxelBoxSettings.Saturation);grading.contrast.Override(VoxelBoxSettings.Contrast);grading.postExposure.Override(Mathf.Log(Mathf.Max(0.01f,VoxelBoxSettings.Brightness),2f));
 bloom.softKnee.Override(0.65f);bloom.diffusion.Override(6f);bloom.clamp.Override(65472f);switch(VoxelBoxSettings.AntiAliasing){case 0:layer.antialiasingMode=PostProcessLayer.Antialiasing.None;break;case 1:layer.antialiasingMode=PostProcessLayer.Antialiasing.FastApproximateAntialiasing;break;case 2:layer.antialiasingMode=PostProcessLayer.Antialiasing.SubpixelMorphologicalAntialiasing;break;default:layer.antialiasingMode=PostProcessLayer.Antialiasing.TemporalAntialiasing;break;}}
}
