using UnityEngine;
public static class VoxelBoxSettingsGUI {
 public static int DrawTabs(int tab){string[] n={"GRAFIK","WELT","STEUERUNG","AUDIO","GAMEPLAY","SPIELERPROFIL"};GUILayout.BeginHorizontal();for(int i=0;i<n.Length;i++)if(GUILayout.Button(n[i],i==tab?VoxelBoxUI.TabActive:VoxelBoxUI.Tab,GUILayout.Height(42)))tab=i;GUILayout.EndHorizontal();GUILayout.Space(12);return tab;}
 public static void Draw(int tab,bool inGame){
  if(tab==0)DrawGraphics(); else if(tab==1)DrawWorld(inGame); else if(tab==2)DrawControls(); else if(tab==3)DrawAudio(); else if(tab==4)DrawGameplay(); else DrawProfile();
 }
 static void DrawGraphics(){GUILayout.Label("GRAFIK",VoxelBoxUI.Header);GUILayout.Label("Darstellung, Post Processing und Qualität",VoxelBoxUI.Small);GUILayout.Space(8);
  GUILayout.Label("Auflösung:  "+Screen.width+" × "+Screen.height+(Screen.fullScreen?"  •  Vollbild":"  •  Fenster"),VoxelBoxUI.Label);
  GUILayout.BeginHorizontal();if(GUILayout.Button(Screen.fullScreen?"FENSTERMODUS":"VOLLBILD",VoxelBoxUI.Button,GUILayout.Height(38)))Screen.fullScreen=!Screen.fullScreen;if(GUILayout.Button("NATIVE AUFLÖSUNG",VoxelBoxUI.Button,GUILayout.Height(38))){var r=Screen.currentResolution;Screen.SetResolution(r.width,r.height,Screen.fullScreen);}GUILayout.EndHorizontal();
  GUILayout.Space(8);GUILayout.Label("Sichtweite (Chunks): "+VoxelBoxSettings.ViewDistance,VoxelBoxUI.Label);VoxelBoxSettings.ViewDistance=Mathf.RoundToInt(GUILayout.HorizontalSlider(VoxelBoxSettings.ViewDistance,4,32));
  bool v=GUILayout.Toggle(VoxelBoxSettings.Shadows,"  Echtzeit-Schatten",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.Shadows)VoxelBoxSettings.Shadows=v;
  GUILayout.Label("Schattenqualität: "+(VoxelBoxSettings.ShadowQualityLevel==0?"Niedrig":VoxelBoxSettings.ShadowQualityLevel==1?"Hoch":"Sehr hoch"),VoxelBoxUI.Label);int sq=Mathf.RoundToInt(GUILayout.HorizontalSlider(VoxelBoxSettings.ShadowQualityLevel,0,2));if(sq!=VoxelBoxSettings.ShadowQualityLevel)VoxelBoxSettings.ShadowQualityLevel=sq;
  GUILayout.Label("Schattendistanz: "+VoxelBoxSettings.ShadowDistance.ToString("0")+" m",VoxelBoxUI.Label);float sd=GUILayout.HorizontalSlider(VoxelBoxSettings.ShadowDistance,40,500);if(Mathf.Abs(sd-VoxelBoxSettings.ShadowDistance)>1)VoxelBoxSettings.ShadowDistance=sd;
  v=GUILayout.Toggle(VoxelBoxSettings.PostProcessing,"  Post Processing",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.PostProcessing)VoxelBoxSettings.PostProcessing=v;
  v=GUILayout.Toggle(VoxelBoxSettings.Bloom,"  Bloom",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.Bloom)VoxelBoxSettings.Bloom=v;
  GUILayout.Label("Bloom-Stärke: "+VoxelBoxSettings.BloomIntensity.ToString("0.0"),VoxelBoxUI.Label);float bi=GUILayout.HorizontalSlider(VoxelBoxSettings.BloomIntensity,0,5);if(Mathf.Abs(bi-VoxelBoxSettings.BloomIntensity)>.02f)VoxelBoxSettings.BloomIntensity=bi;
  v=GUILayout.Toggle(VoxelBoxSettings.AmbientOcclusion,"  Ambient Occlusion",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.AmbientOcclusion)VoxelBoxSettings.AmbientOcclusion=v;
  string[] aa={"Aus","FXAA","SMAA","TAA"};GUILayout.Label("Anti-Aliasing: "+aa[VoxelBoxSettings.AntiAliasing],VoxelBoxUI.Label);int av=Mathf.RoundToInt(GUILayout.HorizontalSlider(VoxelBoxSettings.AntiAliasing,0,3));if(av!=VoxelBoxSettings.AntiAliasing)VoxelBoxSettings.AntiAliasing=av;
  v=GUILayout.Toggle(VoxelBoxSettings.VSync,"  VSync",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.VSync)VoxelBoxSettings.VSync=v;
  GUILayout.Label("Helligkeit: "+VoxelBoxSettings.Brightness.ToString("0.00"),VoxelBoxUI.Label);float br=GUILayout.HorizontalSlider(VoxelBoxSettings.Brightness,.65f,1.35f);if(Mathf.Abs(br-VoxelBoxSettings.Brightness)>.005f)VoxelBoxSettings.Brightness=br;
  GUILayout.Space(5);GUILayout.Label("ATMOSPHÄRE",VoxelBoxUI.Header);
  GUILayout.Label("Farbwärme: "+VoxelBoxSettings.Warmth.ToString("0")+(VoxelBoxSettings.Warmth>0?"  • warm":""),VoxelBoxUI.Label);float wt=GUILayout.HorizontalSlider(VoxelBoxSettings.Warmth,-30f,50f);if(Mathf.Abs(wt-VoxelBoxSettings.Warmth)>.1f)VoxelBoxSettings.Warmth=wt;
  GUILayout.Label("Farbsättigung: "+VoxelBoxSettings.Saturation.ToString("0"),VoxelBoxUI.Label);float sat=GUILayout.HorizontalSlider(VoxelBoxSettings.Saturation,-40f,40f);if(Mathf.Abs(sat-VoxelBoxSettings.Saturation)>.1f)VoxelBoxSettings.Saturation=sat;
  GUILayout.Label("Kontrast: "+VoxelBoxSettings.Contrast.ToString("0"),VoxelBoxUI.Label);float con=GUILayout.HorizontalSlider(VoxelBoxSettings.Contrast,-30f,30f);if(Mathf.Abs(con-VoxelBoxSettings.Contrast)>.1f)VoxelBoxSettings.Contrast=con;
  GUILayout.Label("Umgebungsschatten: "+VoxelBoxSettings.AOIntensity.ToString("0.00"),VoxelBoxUI.Label);float aoi=GUILayout.HorizontalSlider(VoxelBoxSettings.AOIntensity,0f,2f);if(Mathf.Abs(aoi-VoxelBoxSettings.AOIntensity)>.01f)VoxelBoxSettings.AOIntensity=aoi;
  v=GUILayout.Toggle(VoxelBoxSettings.WaterReflection,"  Wasserreflexion",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.WaterReflection)VoxelBoxSettings.WaterReflection=v;v=GUILayout.Toggle(VoxelBoxSettings.WaterEffects,"  Wassereffekte / Wellen",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.WaterEffects)VoxelBoxSettings.WaterEffects=v;v=GUILayout.Toggle(VoxelBoxSettings.WeatherEffects,"  Wettereffekte",VoxelBoxUI.Label);if(v!=VoxelBoxSettings.WeatherEffects)VoxelBoxSettings.WeatherEffects=v;
 }
 static void DrawWorld(bool inGame){GUILayout.Label("WELT",VoxelBoxUI.Header);GUILayout.Label(inGame?"Welt, Tageszeit und Atmosphäre werden im Pause-Menü verwaltet.":"Welteinstellungen werden beim Start der Welt aktiv.",VoxelBoxUI.Label);GUILayout.Space(10);GUILayout.Label("Standard-Sichtweite: "+VoxelBoxSettings.ViewDistance+" Chunks",VoxelBoxUI.Label);}
 static void DrawControls(){GUILayout.Label("STEUERUNG",VoxelBoxUI.Header);GUILayout.Label("Tastatur & Maus",VoxelBoxUI.Small);GUILayout.Space(8);GUILayout.BeginVertical(VoxelBoxUI.Card);GUILayout.Label("MAUS",VoxelBoxUI.Header);GUILayout.Label("Linksklick  •  Block abbauen / Werkzeug benutzen\nRechtsklick  •  Block setzen\nMausrad  •  Auswahl wechseln",VoxelBoxUI.Label);GUILayout.Label("Maus-Empfindlichkeit  "+GameInputManager.Sensitivity.ToString("0.0"),VoxelBoxUI.Label);GameInputManager.Sensitivity=GUILayout.HorizontalSlider(GameInputManager.Sensitivity,1f,10f);GUILayout.EndVertical();GUILayout.Space(6);GUILayout.BeginVertical(VoxelBoxUI.Card);GUILayout.Label("BEWEGUNG & SPIEL",VoxelBoxUI.Header);GUILayout.Label("W A S D  •  Bewegen        SPACE  •  Springen / Fliegen\nE  •  Block-Auswahl         ESC  •  Pause / Menü\nH  •  PNG-Screenshot        M  •  Minecart ein-/aussteigen",VoxelBoxUI.Label);GUILayout.EndVertical();GUILayout.Space(6);GUILayout.BeginVertical(VoxelBoxUI.Card);GUILayout.Label("CREATIVE",VoxelBoxUI.Header);GUILayout.Label("Copy Start / End  •  Bereich markieren\nPaste  •  Auswahl einsetzen\nTNT  •  Creative-Sprengwerkzeug\nWorkshop 8×8×8  •  Custom Block erstellen\nTAB im Workshop  •  UI bedienen / Kamera freigeben",VoxelBoxUI.Label);GUILayout.EndVertical();}
 static void DrawAudio(){GUILayout.Label("AUDIO",VoxelBoxUI.Header);GUILayout.Label("Der Musikplayer und seine Lautstärke stehen im Pause-Menü unter Audio zur Verfügung.",VoxelBoxUI.Label);}
 static void DrawProfile(){GUILayout.Label("SPIELERPROFIL",VoxelBoxUI.Header);GUILayout.Label("Deine lokale The-Voxel-Box-Statistik",VoxelBoxUI.Small);GUILayout.Space(8);GUILayout.BeginHorizontal();GUILayout.BeginVertical(VoxelBoxUI.Card,GUILayout.Width(470));GUILayout.Label("SPIELZEIT & BAUEN",VoxelBoxUI.Header);GUILayout.Label("Spielzeit gesamt:  "+PlayerProfileManager.TimeText(PlayerProfileManager.TotalSeconds)+"\nAktuelle Session:  "+PlayerProfileManager.TimeText(PlayerProfileManager.SessionSeconds)+"\n\nBlöcke gesetzt:  "+PlayerProfileManager.Placed.ToString("N0")+"\nBlöcke abgebaut:  "+PlayerProfileManager.Removed.ToString("N0")+"\nStein gesetzt:  "+PlayerProfileManager.Stone.ToString("N0")+"\nHolz/Baum gesetzt:  "+PlayerProfileManager.Wood.ToString("N0")+"\nCopy/Paste-Blöcke:  "+PlayerProfileManager.Paste.ToString("N0")+"\nTNT entfernte Blöcke:  "+PlayerProfileManager.Tnt.ToString("N0"),VoxelBoxUI.Label);GUILayout.EndVertical();GUILayout.Space(12);GUILayout.BeginVertical(VoxelBoxUI.Card);GUILayout.Label("PERFORMANCE & SYSTEM",VoxelBoxUI.Header);GUILayout.Label("Session-Durchschnitt:  "+PlayerProfileManager.SessionFPS.ToString("0")+" FPS\nLangzeit-Durchschnitt:  "+PlayerProfileManager.LifetimeFPS.ToString("0")+" FPS\n\n"+PlayerProfileManager.Hardware(),VoxelBoxUI.Label);GUILayout.EndVertical();GUILayout.EndHorizontal();}

 static void DrawGameplay(){GUILayout.Label("GAMEPLAY",VoxelBoxUI.Header);GUILayout.Label("Creative-Modus\nCopy & Paste • TNT • Custom Workshop • Minecart",VoxelBoxUI.Label);GUILayout.Space(12);GUILayout.Label("Die Spielmitte bleibt bewusst frei von permanenten Hinweisen und FPS-Anzeigen.",VoxelBoxUI.Small);}
}
