using UnityEngine;
using System;using System.IO;using System.IO.Compression;using System.Collections.Generic;using System.Threading.Tasks;
// 0.9.9 - native, preconverted fixed Block Island world. No .Island/LZMA runtime import.
public static class BlockIslandNativeWorld {
 const int MaxCachedColumns=4096; class C{public ushort[] id=new ushort[16*16*256];public byte[] meta=new byte[16*16*256];public int[] height=new int[256];public ushort sectionMask;public int stamp;}
 static readonly Dictionary<long,C> cache=new Dictionary<long,C>();static readonly HashSet<long> missing=new HashSet<long>(),pending=new HashSet<long>();static readonly object gate=new object();static int stamp;static string root;static int hotX=int.MinValue,hotZ=int.MinValue;static C hotC;
 static readonly string[] LegacyNames=new string[]{
        "Grass",
        "Dirt",
        "Rock",
        "Nebula",
        "Sand",
        "Dark Wood",
        "Stone 2",
        "snow",
        "Light Wood",
        "Spruce Wood",
        "Birch Wood",
        "Funiere2",
        "baum4",
        "Green Leaf",
        "Birch Leaf",
        "Red Leaf",
        "Fence2",
        "Fence",
        "09",
        "Green FX",
        "Stair",
        "Stair2",
        "Blume 2",
        "Gorilla",
        "Metall",
        "red Marmor",
        "Marmor 1",
        "pizza",
        "grey stone",
        "xschild",
        "Cross Stone",
        "Quarz 3",
        "Glas4",
        "Wolf",
        "Water Plane 500",
        "Stroh",
        "Funiere3",
        "14",
        "Lighting Spark",
        "Bodenweg2",
        "sandstone",
        "leuchtend",
        "16",
        "Christine",
        "FX Magic 1",
        "Gemini",
        "Bridge 1",
        "Glas2",
        "Sagitarius",
        "Minecart 1",
        "Blue FX",
        "Blue Star",
        "Heinrich",
        "Earth",
        "Omega Fighter",
        "Glas2",
        "flame",
        "Regal Normal",
        "Waterfall",
        "baum2",
        "Funiere1",
        "Messing Stone",
        "Bear",
        "Cancer",
        "01",
        "Leo",
        "Metall",
        "06",
        "aHolz",
        "baum1",
        "Roter Stein 2",
        "29",
        "Dust",
        "SunFloor",
        "30",
        "Dragon",
        "Quarz 4",
        "Fire",
        "Quarder",
        "Glas3",
        "Red Stone",
        "Marble",
        "Heaven",
        "Muster1",
        "24",
        "Moos Stone",
        "Holz 4",
        "fliesen 1",
        "Ice",
        "21",
        "Roter Stein 3",
        "Plattenweg",
        "LAVA",
        "Stone",
        "Muster",
        "Moos Stone",
        "Stone21",
        "Bridge 3",
        "Dach 2",
        "Mamor2",
        "Grass",
        "Dirt",
        "Spruce Leaf",
        "Pink Leaf",
        "Holz",
        "Holz",
        "Holz 2",
        "Brick2",
        "planken",
        "17",
        "22",
        "musterstone",
        "13",
        "32",
        "Ore1",
        "Ore2",
        "Gold",
        "Marmor2",
        "23",
        "04",
        "31",
        "Marmor",
        "Holz 3",
        "Mauer",
        "Brick",
        "Yellow Leaf",
        "Capricorn",
        "Jukebox",
        "28",
        "Schrank",
        "25",
        "Circle FX Light",
        "Ancient Statue",
        "Circle FX Ice",
        "19",
        "Pillar Greek",
        "Pillar Red",
        "12",
        "Siren",
        "FCE",
        "Life Stream",
        "Lion Statue",
        "26",
        "Brick3",
        "Orange FX",
        "Minecart Track 2",
        "03",
        "Pilz",
        "10",
        "strauss",
        "Blume",
        "Tulpe 3",
        "Grass",
        "Tulpe 1",
        "Tulpe 2",
        "Couch3",
        "Dach 1",
        "fireworks",
        "Ske2",
        "light yellow",
        "Spider",
        "Stag",
        "Pig",
        "Duck 1",
        "Duck 2",
        "Boar",
        "Waterfall V1",
        "Material Ball",
        "27",
        "Graffin Statue",
        "Aries",
        "butterfly green",
        "butterfly blue",
        "FX Magic 2",
        "butterfly red",
        "Circle FX Fire",
        "Red FX",
        "Flora4",
        "05",
        "Taurus",
        "Video",
        "2001",
        "20",
        "07",
        "02",
        "baum3",
        "08",
        "Water Plane 4x3",
        "Ske3",
        "Ske4",
        "Skel5",
        "Martha",
        "Isolde",
        "Nadine",
        "Jenny",
        "Stephanie",
        "18",
        "Elfriede",
        "light blue",
        "Christian",
        "Darius",
        "Udo",
        "Michael",
        "Alfred",
        "Scorpio",
        "Bernd",
        "light red",
        "lighting field",
        "Couch2",
        "Couch1",
        "Planet",
        "Circle FX Dark",
        "Leaves",
        "Red Star",
        "Siren",
        "Steinblock",
        "Table",
        "Parkchair",
        "Cactus",
        "Cyclone",
        "Latern",
        "Steinkreuz",
        "Planet smal",
        "Splash",
        "fountain",
        "Fountain",
        "light green",
        "Magic Gate",
        "Meteor",
        "Mystic Pool",
        "Fireworks",
        "Sparkle Rising",
        "blowing leaves",
        "Minecart Track 1",
        "smoke",
        "15",
        "Clown",
        "SunTempleFloor",
        "Skeleton",
        "11",
        "Sphere FX",
        "Libra",
        "butterfly yellow",
        "The Cross",
        "Virgo",
        "Blitze",
        "Bridge 2",
        "Yellow Star",
        "Magic smal 3",
        "Magic floating 2",
        "Magic smal 1",
        "Magica",
        "Bed",
        "Minecart 2",
        "Water"
 };
 static readonly Dictionary<int,Block> mapped=new Dictionary<int,Block>();
 static string Root{get{return root??Path.Combine(Application.streamingAssetsPath,"BlockIslandNative/region");}} static long Key(int x,int z){return ((long)x<<32)^(uint)z;} static int FD(int a,int b){int q=a/b,r=a%b;return r!=0&&((r<0)!=(b<0))?q-1:q;} static int Mod(int a,int b){int r=a%b;return r<0?r+b:r;}
 public static bool Available{get{return Directory.Exists(Root);}} public static void Begin(){root=Path.Combine(Application.streamingAssetsPath,"BlockIslandNative/region");lock(gate){cache.Clear();missing.Clear();pending.Clear();stamp=0;}mapped.Clear();hotC=null;hotX=hotZ=int.MinValue;Debug.Log("BLOCK ISLAND 0.9.9 NATIVE: preconverted fixed world online. No legacy .Island runtime dependency.");} public static void End(){lock(gate){cache.Clear();missing.Clear();pending.Clear();}mapped.Clear();hotC=null;}
 public static bool IsWorldColumnReady(int wx,int wz){int x0=wx*Chunk.X_SIZE,z0=wz*Chunk.Z_SIZE,a=FD(x0,16),b=FD(x0+Chunk.X_SIZE-1,16),c=FD(z0,16),d=FD(z0+Chunk.Z_SIZE-1,16);lock(gate){for(int x=a;x<=b;x++)for(int z=c;z<=d;z++){long k=Key(x,z);if(!cache.ContainsKey(k)&&!missing.Contains(k))return false;}return true;}}
 public static void RequestWorldColumn(int wx,int wz){int x0=wx*Chunk.X_SIZE,z0=wz*Chunk.Z_SIZE,a=FD(x0,16),b=FD(x0+Chunk.X_SIZE-1,16),c=FD(z0,16),d=FD(z0+Chunk.Z_SIZE-1,16);for(int x=a;x<=b;x++)for(int z=c;z<=d;z++)Request(x,z);} static void Request(int x,int z){long k=Key(x,z);lock(gate){if(cache.ContainsKey(k)||missing.Contains(k)||pending.Contains(k))return;pending.Add(k);}Task.Run(()=>{C q=Load(x,z);lock(gate){pending.Remove(k);if(q==null)missing.Add(k);else{q.stamp=++stamp;cache[k]=q;}}});}
 public static bool Raw(int x,int y,int z,out ushort id,out byte meta){id=0;meta=0;if(y<0||y>255)return false;int cx=FD(x,16),cz=FD(z,16);C c=(cx==hotX&&cz==hotZ)?hotC:Get(cx,cz);if(cx!=hotX||cz!=hotZ){hotX=cx;hotZ=cz;hotC=c;}if(c==null)return false;int i=(y*16+Mod(z,16))*16+Mod(x,16);id=c.id[i];meta=c.meta[i];return true;}
 public static void FillChunk(DataBlock[] dst,int ox,int oy,int oz){if(dst==null||dst.Length<Chunk.X_SIZE*Chunk.Y_SIZE*Chunk.Z_SIZE)return;int i=0;for(int z=0;z<Chunk.Z_SIZE;z++)for(int y=0;y<Chunk.Y_SIZE;y++)for(int x=0;x<Chunk.X_SIZE;x++,i++)dst[i]=Sample(ox+x,oy+y,oz+z);}
 public static DataBlock Sample(int x,int y,int z){ushort id;byte dir;if(!Raw(x,y,z,out id,out dir)||id==0)return default(DataBlock);Block b=Map(id);return b!=null?new DataBlock(b,(BlockDirection)dir):default(DataBlock);} public static int SurfaceY(int x,int z){C c=Get(FD(x,16),FD(z,16));if(c==null)return 64;int h=c.height[Mod(z,16)*16+Mod(x,16)];return Mathf.Clamp(h>0?h-1:0,0,255);}
 public static bool HasBlocksInWorldChunk(int wx,int wy,int wz){int y0=wy*Chunk.Y_SIZE,y1=y0+Chunk.Y_SIZE-1;if(y1<0||y0>255)return false;int s0=Mathf.Clamp(FD(y0,16),0,15),s1=Mathf.Clamp(FD(y1,16),0,15);ushort mask=0;for(int s=s0;s<=s1;s++)mask|=(ushort)(1<<s);int x0=wx*32,z0=wz*32;for(int x=FD(x0,16);x<=FD(x0+31,16);x++)for(int z=FD(z0,16);z<=FD(z0+31,16);z++){C q=Get(x,z);if(q!=null&&(q.sectionMask&mask)!=0)return true;}return false;}
 static Block Map(ushort id){Block b;if(mapped.TryGetValue(id,out b))return b;if(id==0||id>LegacyNames.Length)return null;string n=LegacyNames[id-1]; /* Block-Island-only restoration mapping: legacy Marble = white walls, Red Stone = red roofs. Native BIR data stays immutable. */ if(String.Equals(n,"Marble",StringComparison.OrdinalIgnoreCase)) b=Find("Block Island White Stone"); else if(String.Equals(n,"Red Stone",StringComparison.OrdinalIgnoreCase)) b=Find("Block Island Red Stone"); else b=BlockSet.instance!=null?BlockSet.instance.FindBlock(n):null;if(b is GameObjectBlock)b=null;if(b==null)b=Alias(n);mapped[id]=b;return b;}
 static Block Find(string n){return BlockSet.instance!=null?BlockSet.instance.FindBlock(n):null;} static Block Alias(string n){string s=(n??"").ToLowerInvariant();Block b=null;if(s.Contains("water"))b=Find("Water");else if(s.Contains("grass"))b=Find("Grass");else if(s.Contains("dirt")||s.Contains("erde"))b=Find("Dirt");else if(s.Contains("sand"))b=Find("Sand");else if(s.Contains("snow"))b=Find("Snow");else if(s.Contains("leaf")||s.Contains("blatt"))b=Find("Green Leaf");else if(s.Contains("wood")||s.Contains("holz"))b=Find("Dark Wood");else if(s.Contains("glass")||s.Contains("glas"))b=Find("BI Stained Glass")??Find("Glass");else if(s.Contains("flower")||s.Contains("blume"))b=Find("Flower 1");else if(s.Contains("fung")||s.Contains("pilz"))b=Find("Fungus 1");else if(s.Contains("fence")||s.Contains("zaun"))b=Find("Fence");else if(s.Contains("stair")||s.Contains("treppe"))b=Find("Stair");else if(s.Contains("brick")||s.Contains("mauer"))b=Find("BI Red Brick")??Find("Tanviir Castle Wall");else if(s.Contains("marble")||s.Contains("marmor"))b=Find("Tanviir Pale Stone")??Find("Stone");else if(s.Contains("stone")||s.Contains("rock")||s.Contains("stein"))b=Find("Stone")??Find("Rock");else if(s.Contains("roof")||s.Contains("dach"))b=Find("Tanviir Red Tile")??Find("BI Red Brick");else if(s.Contains("metal")||s.Contains("metall"))b=Find("Tanviir Iron Block")??Find("Stone");if(b==null)b=Find("Tanviir Weathered Stone")??Find("Stone")??Find("Rock");return b is GameObjectBlock?null:b;}
 static C Get(int x,int z){long k=Key(x,z);C c;lock(gate){if(cache.TryGetValue(k,out c)){c.stamp=++stamp;return c;}if(missing.Contains(k))return null;}c=Load(x,z);lock(gate){if(c==null){missing.Add(k);return null;}c.stamp=++stamp;cache[k]=c;return c;}}
 static C Load(int cx,int cz){try{int rx=FD(cx,32),rz=FD(cz,32),regionLocalX=Mod(cx,32),regionLocalZ=Mod(cz,32);string p=Path.Combine(Root,"r."+rx+"."+rz+".bir");if(!File.Exists(p))return null;byte[] packed;using(FileStream f=File.OpenRead(p)){byte[] m=new byte[4];if(f.Read(m,0,4)!=4||m[0]!='B'||m[1]!='I'||m[2]!='R'||m[3]!='1')return null;f.Position=4L+(regionLocalX+regionLocalZ*32)*12L;ulong off=ReadU64(f);uint len=ReadU32(f);if(off==0||len==0)return null;f.Position=(long)off;packed=new byte[len];ReadFully(f,packed,0,packed.Length);}byte[] raw=Inflate(packed);using(BinaryReader br=new BinaryReader(new MemoryStream(raw))){C c=new C();c.sectionMask=br.ReadUInt16();for(int i=0;i<256;i++)c.height[i]=br.ReadUInt16();for(int s=0;s<16;s++)if((c.sectionMask&(1<<s))!=0){int sy=br.ReadByte();for(int i=0;i<4096;i++){int localY=(i>>8)&15,localZ=(i>>4)&15,localX=i&15,di=((sy*16+localY)*16+localZ)*16+localX;c.id[di]=br.ReadUInt16();}for(int i=0;i<4096;i++){int localY=(i>>8)&15,localZ=(i>>4)&15,localX=i&15,di=((sy*16+localY)*16+localZ)*16+localX;c.meta[di]=br.ReadByte();}}return c;}}catch(Exception e){Debug.LogWarning("BLOCK ISLAND NATIVE read failed "+cx+","+cz+": "+e.Message);return null;}}
 static byte[] Inflate(byte[] p){using(var input=new MemoryStream(p)){if(p.Length>2)input.Position=2;using(var ds=new DeflateStream(input,CompressionMode.Decompress))using(var output=new MemoryStream()){ds.CopyTo(output);return output.ToArray();}}} static ulong ReadU64(Stream s){byte[] b=new byte[8];ReadFully(s,b,0,8);return BitConverter.ToUInt64(b,0);}static uint ReadU32(Stream s){byte[] b=new byte[4];ReadFully(s,b,0,4);return BitConverter.ToUInt32(b,0);}static void ReadFully(Stream s,byte[] b,int o,int n){while(n>0){int r=s.Read(b,o,n);if(r<=0)throw new EndOfStreamException();o+=r;n-=r;}}
}
